### ISSUE TITLE
Gen fast-forwards through optional characters

### ISSUE THREAD

**Issue by hudson-ai** [hudson-ai/guidance#16]
`LLInterpreter` fast-forwards the character "a" in the following grammars:
`gen(regex="a?")`, and `gen(regex="a*")` 

And it fast-forwards all three of "a" "b" "c" in these:
`gen(regex="(abc)?")`, and `gen(regex="(abc)*")` 

Note that when followed by other terms, I do NOT observe the fast-forwarding behavior:
`gen(regex="a?d")`, and `gen(regex="a?d?")` 

@mmoskal I believe we talked about this before but I didn't see an identical open issue. I believe the context of that conversation was the new behavior of `process_prompt` where we no longer get BOS tokens in it.

**Comment by mmoskal** [comment]
I think it's just that gen wants to be non empty... Will fix!

**Comment by hudson-ai** [comment]
@mmoskal could this also be the cause of `("x" + gen(regex="y?"))` being unable to match just `"x"`? If you don't think so I will open a separate issue

**Comment by mmoskal** [comment]
yeah, the same.

I will for such nullable lexemes, I will rewrite them to optional(lexeme) at the CFG level

**Comment by hudson-ai** [comment]
Ok, wonderful
