### ISSUE TITLE
EOS and nullable lexemes

### ISSUE THREAD

**Issue by hudson-ai** [hudson-ai/guidance#18]
```
greedy_grammar(body=lexeme(r"\d+")+lexeme(r"x?"))
```

This is accepting at 1, 123, etc.
It is accepting and done at 1x, 123x, etc.
 
When it's sitting at 1, 123, etc. it indeed allows you to send the EOS token, but that doesn't make it done. I thought maybe I might need a second EOS if the issue was that the first one only completed the first lexeme, but as far as I can tell, this grammar will allow any number of EOS tokens after some digits, and it will never be done...

**Comment by mmoskal** [comment]
should work
