### ISSUE TITLE
remove code duplication between models/_azure_guidance.py and models/_model.py

### ISSUE THREAD

**Issue by mmoskal** [hudson-ai/guidance#2]

**Comment by hudson-ai** [comment]
Wrote an LLParser class to provide a higher level interface to the generation control-loop. It felt like the most natural place to put the logic to handle the progress `list[dict]`, even though the AzureGuidanceEngine doesn't directly use the parser. Feels a bit hacky at the moment, but here's a starting place to iterate from.

https://github.com/hudson-ai/guidance/blob/25f2162b3c220bf067fe69dfd70b641239076c21/guidance/_parser.py#L113
