### ISSUE TITLE
llama_cpp tests are failing, unsure if test misspecification..?

### ISSUE THREAD

**Issue by hudson-ai** [hudson-ai/guidance#22]
There are a number of tests in `tests/model_specific/test_llama_cpp.py` that explicitly use the BOS token, causing a panic in `llguidance`... @mmoskal do you think these tests are nonsense, or is there something to fix here?

Example of one of the failing tests 
(run them all yourself with `pytest tests/model_specific/test_llama_cpp.py --selected_model=hfllama7b`):
```python
def test_llama_cpp_exactly_one_batch(llamacpp_model, selected_model_info):
    lm = llamacpp_model
    batch_size = lm.engine.model_obj.n_batch
    long_str = lm.engine.tokenizer.bos_token.decode("utf-8") * batch_size
    lm += long_str + gen(max_tokens=10)
    assert len(str(lm)) > len(long_str)
```

The panic is being raised here in `_parser.py`:
```python
    def _process_prompt(self, prompt: bytes, ensure_bos_token: bool) -> list[int]:
>       prompt_tokens = self.ll_interpreter.process_prompt(
            self.tokenizer.encode(prompt)
        )
E       pyo3_runtime.PanicException: range start index 1 out of range for slice of length 0
```

**Comment by mmoskal** [comment]
So I now round-trip the BOS token. The EOS token can't be roundtripped (I make it empty). I think it would be better to use some other token in this test though - "\x03" would be probably a good choice.

**Comment by hudson-ai** [comment]
Do we need the roundtripping? (I genuinely don't know). It may be a bit odd if EOS is the same as BOS...
But definitely switching to `\x03`, thanks
