### ISSUE TITLE
`Mock` no longer chooses `EOS` when its prepared string stops matching

### ISSUE THREAD

**Issue by hudson-ai** [hudson-ai/guidance#6]
This runs forever rather than stopping when it should
```
lm = models.Mock(b"<s>1234233234<s>")
grammar = one_or_more(select(["1", "2"])
lm += grammar
```

**Comment by hudson-ai** [comment]
@mmoskal I'm seeing some strange behavior with grammars that end in optional tokens (or at least optional bytes with the `ByteTokenizer`).

E.g.
```python
g = "a" + optional("b")
```

When we call mid-process, we get the following mask (I'll just list the valid tokens) and response (I'll just show the important keys):
```python
ll_interpreter.mid_process(0, [])
>> {97, 256}
>> {"progress":[{"object":"text","str":"a","hex":"61","num_tokens":1, ...}],"stop":false,"backtrack":0,"ff_tokens":[], ...}
```
Where 98 is `b'b'` and 256 is the EOS token.

If we feed it 98, we get an expected response:
```python
ll_interpreter.mid_process(0, [98])
>> None
>> {"progress":[{"object":"text","str":"b","hex":"62","num_tokens":1, ...}, ...],"stop":true,"backtrack":0,"ff_tokens":[], ...}
```
All good, that means we're done.

But if we instead gave it 256, let's see what happens
```python
ll_interpreter.mid_process(0, [256])
>> None
>> {"progress":[{"object":"text","str":"","hex":"","num_tokens":1, ...}, ...],"stop":false,"backtrack":1,"ff_tokens":[], ...}
```
Ok, makes sense. We need to backtrack because this token is "hidden", but then we should get a "stop" signal, right?
```python
ll_interpreter.mid_process(1, [])
>> None
>> {"progress":[{"object":"text","str":"","hex":"","num_tokens"::18446744073709551615, ...}, ...],"stop":false,"backtrack":0,"ff_tokens":[], ...}
```
Uh oh, an overflow AND we don't get a stop signal...

I don't think that this is terribly problematic as I suppose I can catch stop tokens further up the stack, but it does seem to indicate something odd going on...

**Comment by hudson-ai** [comment]
And actually just caught that a single "naked" `optional("a")` gets fast-forwarded completely...

**Comment by mmoskal** [comment]
I think it may be related to #4 - I was looking into it, but got distracted. Hopefully Monday!

**Comment by hudson-ai** [comment]
Sounds good! I got distracted too... I think we can drive a lot home next week. Have a good weekend :)

**Comment by hudson-ai** [comment]
FYI #4 is fixed on reinstalling llguidance, but this one is still an issue

**Comment by mmoskal** [comment]
@hudson-ai is this OK now?

**Comment by hudson-ai** [comment]
@mmoskal still getting the overflow and no "stop" signal with a fresh re-install of llguidance
